apiVersion: 1
# Note: Credentials are loaded from environment variables.
# Set POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB in compose/.env
datasources:
  - name: paku-postgres
    uid: DS_POSTGRESQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: $POSTGRES_USER
    isDefault: true
    jsonData:
      database: $POSTGRES_DB
      sslmode: "disable"
      postgresVersion: 1600
    secureJsonData:
      password: $POSTGRES_PASSWORD
