apiVersion: 1
datasources:
  - name: Paku-Postgres
    uid: paku-pg
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    database: paku
    user: paku
    secureJsonData:
      password: paku
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
