apiVersion: 1
datasources:
  - name: Paku Postgres
    uid: paku_pg
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: paku
    secureJsonData:
      password: paku
    jsonData:
      database: paku
      sslmode: disable
      postgresVersion: 1500
